### ISSUE TITLE
Only have crash directory exist when there are minidumps

### ISSUE THREAD

**Issue by vthib** [EmbarkStudios/sentry-contrib-rust#12]
I would like to be able to use this crate but not have the crash directory always exist.
That would mean:
- create the crash directory only when a minidump is caught. AFAICT this is already supposed to be done by breakpad, but this crate still creates the crash directory early.
- remove the crash directory once all minidumps are read and removed at startup (if empty of course).

This could be configurable as well, i suppose that not everyone necessarily wants this behavior.

An alternative could be to let the user handle this directory, ie:
- this crate does nothing about the directory (or we can just turn off the early creation). breakpad will still create the directory when a minidump is generated
- the user can create the crash directory early if we wishes
- a callback or something is used to notify the user when the crash dir has been read at startup, so that the user can chose to delete it.

Either way, i'm totally ok with doing a PR for it, if you agree on its usefulness and have a preferred design.

**Comment by Jake-Shadle** [comment]
I'd accept a PR for any way you want to do it, as we don't actually use the high level crate at all any longer as we don't use sentry-core at all and use our own version due to various limitations with the sentry-core API.

**Comment by vthib** [comment]
Well, it turns out that breakpad do not create this directory, so we can forget about this idea.
